export const ActionTypes = {
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTION_PRODUCT: 'SELECTION_PRODUCT',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT'
}